### ISSUE TITLE
Add upload to (S)FTP/S3 option

### ISSUE THREAD

**Issue by phortuin** [voorhoede/fastatic#122]
If pulling my static site through fastatic is the last step of my development process, I probably want to deploy the site after that. Having an option to automatically upload all files to a folder on an (S)FTP, or S3 bucket, is probably very useful

**Comment by jbmoelker** [comment]
Shouldn't each tool just do one thing and do that well? This project's UX is currently extremely simple. The more options we add, the more complexity we add. Both in code and UX. From [CONTRIBUTING.md](https://github.com/voorhoede/fastatic/blob/master/CONTRIBUTING.md):

> The aim of this project is to allow developers to make every static website as fast as possible, with just one command: `fastatic`. Fastatic must work-out-of-box with zero configuration required. If a new feature does require configuration it must be on opt-in basis.
>
> Contributions should be aimed towards this and / or improve the development workflow.

Also, I wonder if you meant to file this under [fastatic-app](https://github.com/voorhoede/fastatic-app) instead of fastatic.

**Comment by phortuin** [comment]
Ah yeah this was supposed to be in fastatic-app :)
